- name: Create containerd configuration directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd configuration
  ansible.builtin.command: containerd config default
  register: containerd_config

- name: Modify containerd configuration to use systemd cgroup driver
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes

