- name: Ensure containerd is installed
  ansible.builtin.apt:
    name: containerd
    state: present
    update_cache: yes

- name: Ensure containerd configuration directory exists
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Deploy containerd configuration from template
  ansible.builtin.template:
    src: containerd-config.toml.j2
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: Restart containerd  # This now correctly refers to the handler

