- name: Join worker node to cluster
  ansible.builtin.command: "{{ hostvars[groups['prime_control'][0]]['worker_join'] }}"
  when: inventory_hostname in groups['worker_nodes']
  become: yes
  register: join_result
  changed_when: join_result.rc == 0

# - name: Wait for node to be in Ready state
#   ansible.builtin.shell: |
#     kubectl get node "{{ ansible_default_ipv4.address }}" --no-headers | grep -w "Ready"
#   delegate_to: "{{ groups['prime_control'][0] }}"
#   register: node_status
#   until: node_status.rc == 0
#   retries: 30  # Adjust based on how long worker nodes take to be ready
#   delay: 10

- name: Ensure kubelet is running and enabled
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: yes

