- name: Install kubeadm, kubelet, kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Pin Kubernetes tools to prevent auto-updates
  ansible.builtin.command: apt-mark hold kubelet kubeadm kubectl
  changed_when: false

